name: unit-test

on: [push]

jobs:
  unit-test-on-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]        
        include:
          - goarch: mipsle
            goos: linux        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.4"
      - run: |
          go version
          go test -v ./encryption
      - name: make
        run: make
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }} 

  unit-test-on-win:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.4"
      - run: |
          go version
          go test -v ./encryption
          $env:GOARCH="386"
          go test -v ./encryption
      - name: make
        run: make
