name: unit-test

on: [push]

jobs:
  unit-test-on-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - run: |
          go version
          go test -v ./encryption
          export GOARCH=386
          go test -v ./encryption

  unit-test-on-win:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - run: |
          go version
          go test -v ./encryption
          $env:GOARCH="386"
          go test -v ./encryption
